import type { NeoConfig, NeoTheme } from '../../typings/theme';

export const DefaultLightTheme: NeoTheme = {
  dark: false,
  colors: {
    primary: '#a3e635',
    onPrimary: '#000000',
    secondary: '#facc15',
    onSecondary: '#000000',
    error: '#CC0000',
    onError: '#FFFFFF',
    success: '#00AA44',
    onSuccess: '#FFFFFF',
    warning: '#FFCC00',
    onWarning: '#000000',
    background: '#f5ece7',
    onBackground: '#000000',
    surface: '#d9c2b8',
    onSurface: '#000000',
    border: '#000000',
    shadow: '#000000',
    muted: '#888888',
  },
  radius: 'none',
  borderSize: 'medium',
  shadowSize: 'md',
  animation: true,
  shadow: true,
  border: true,
  animationDuration: 100,
};

export const DefaultDarkTheme: NeoTheme = {
  dark: true,
  colors: {
    primary: '#a3e635',
    onPrimary: '#000000',
    secondary: '#facc15',
    onSecondary: '#000000',
    error: '#CC0000',
    onError: '#FFFFFF',
    success: '#00AA44',
    onSuccess: '#FFFFFF',
    warning: '#FFCC00',
    onWarning: '#000000',
    background: '#111111',
    onBackground: '#F0F0F0',
    surface: '#1E1E1E',
    onSurface: '#F0F0F0',
    border: '#F0F0F0',
    shadow: '#F0F0F0', // coral offset shadow
    muted: '#5E5E5E',
  },
  radius: 'none',
  borderSize: 'medium',
  shadowSize: 'md',
  animation: true,
  shadow: true,
  border: true,
  animationDuration: 150,
};

export const defaultConfig: NeoConfig = {
  borderSize: {
    none: 0,
    thin: 1,
    medium: 2,
    thick: 3,
  },
  radius: {
    none: 0,
    sm: 4,
    md: 8,
    lg: 12,
    full: 999999,
    xl: 16,
  },
  spacing: {
    'xs': 2,
    'sm': 4,
    'md': 8,
    'lg': 12,
    'xl': 18,
    '2xl': 24,
    '3xl': 30,
  },
  shadowSize: {
    sm: 2,
    md: 4,
    lg: 8,
  },
  fontSize: {
    'sm': 12,
    'md': 14,
    'lg': 16,
    'xl': 20,
    '2xl': 24,
    '3xl': 28,
  },
  fonts: {
    medium: 'System',
    bold: 'System',
    normal: 'System',
  },
};
